-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgc+STwrOLCn7hGPpD
52cXM1AzhKVuzpxpMoVqLXCEIxagCgYIKoZIzj0DAQehRANCAAR6UdJJjd9o44uu
FjomlzJlXjdZ8TQBRtr/tcTmYpr/eMM9/iVvHQaA5fdzJ+5lq/WFaPQ8pPpJgFv6
QLu5rOuN
-----END PRIVATE KEY-----


---Message----
Key generated by Apple Developer Portal

You can create the .p8 file - https://developer.apple.com/account/

Then go to Certificates, Identifiers & Profiles > Keys > add

Select Apple Push Notification service (APNs), put a Key Name (whatever).

Then click on "continue", after "register" and you get it and you can download it.

---------